# 导入数据以及R包
```{r}
# rpkm <- read.csv("Abundant.gene.count.81.csv", header = T, row.names = 1)
# design <- read.csv("Design_74.csv", header = T, row.names = 1)
# rpkm1 <- rpkm[,rownames(design)]
# write.csv(rpkm1, file = "Abundant.gene.count.74.csv")

library(igraph)
library(dplyr)
library(Hmisc)

## 读入OTU/ASV表格，列为样本，行为物种
otu_rare1 <- read.csv('Gene.RPKM.74.csv', header = T, row.names = 1, stringsAsFactors = F)
#otu_rare <- otu_rare1[rowSums(otu_rare1)>30,]
otu_rare <- otu_rare1[,1:70]
otu_rare <- ceiling(otu_rare)
#otu_rare <- as.data.frame(otu_rare)
str(otu_rare)
colnames(otu_rare)

## 选择irrigated and unirrigated samples
irri.samp <- otu_rare1[,1:30]
unirri.samp1 <- otu_rare1[,31:74]

# 随机选择30列样品作图
set.seed(123)  # 设置随机种子以保证结果可复现
unirri.samp <- unirri.samp1[, sample(ncol(unirri.samp1), 30)]

# 合并数据
otu_rare <- cbind(irri.samp, unirri.samp)

## 定义一些颜色
col_g <- "#C1C1C1"
cols <- c("#DEB99B" ,"#5ECC6D", "#5DAFD9", "#7ED1E4", "#EA9527", "#F16E1D" ,"#6E4821", "#A4B423",
          "#C094DF" ,"#DC95D8" ,"#326530", "#50C0C9", "#67C021" ,"#DC69AF", "#8C384F", "#30455C", "#F96C72","#5ED2BF")

trt_id <- c('irrigated','drought') ## 定义样本的关键词，然后从样本名抓取处理的样本
split_otu <- lapply(apply(sapply(trt_id, function(x){grep(x,colnames(otu_rare))}),2, FUN= function(x){otu_rare[,x]}),function(x){x[-(which(rowSums(x)==0)),]})


## 有此处主要聚焦展示绘图方法，构建网络时没有对输入数据进行筛选
g <- lapply(split_otu, function(x){
    #occor <- WGCNA::corAndPvalue(t(x)/colSums(x), method = 'RMT')
    occor<-WGCNA::corAndPvalue(t(x),method = 'pearson')
    mtadj <- multtest::mt.rawp2adjp(unlist(occor$p), proc='BH')
    adpcor <- mtadj$adjp[order(mtadj$index),2]
    occor.p <- matrix(adpcor, dim(t(x)/colSums(x))[2])
    ## R value
    occor.r <- occor$cor
    diag(occor.r) <- 0
    occor.r[occor.p>0.01|abs(occor.r)<0.87] = 0  # 先用RMT获得最佳的r值和p值; irrigated: 0.8736; Unirrigated: 0.7972
    occor.r[is.na(occor.r)]=0
    g <-  graph.adjacency(occor.r, weighted = TRUE, mode = 'undirected')
    # 删除自相关
    g <- simplify(g)
    # 删除孤立节点
    g <- delete.vertices(g, which(degree(g)==0) )
    return(g)
})

save(g, file = 'network_irrigation.rda')
#load('network.rda')
```

# 单图示例
列表`g`中包含三个`igraph`构建的无向网络，我们选取第一个来做下面的演示

## 计算网络模块
```{r}
## 提取第一个网络演示
g1 <- g[[1]]
# plot(g[[1]])

## 设置网络的weight，为计算模块性做准备
E(g1)$correlation <- E(g1)$weight
E(g1)$weight <- abs(E(g1)$weight)
# The proportion of positive and negative edges
sum(E(g1)$weight > 0)
sum(E(g1)$weight < 0)

## 计算网络模块
set.seed(007)
V(g1)$modularity <- membership(cluster_fast_greedy(g1))
```

## 添加节点以及边的颜色
按照模块设置节点的颜色 
选取包含节点数量前18个模块赋予不同的颜色，剩余模块赋予灰色

```{r}
V(g1)$label <- V(g1)$name  # node对应的gene name
V(g1)$label <- NA
modu_sort <- V(g1)$modularity %>% table() %>% sort(decreasing = T) #统计每个模块node的数量
top_num <- 18  # 提取前18个modules
modu_name <- names(modu_sort[1:18])  # name of modules
modu_cols <- cols[1:length(modu_name)]  # color for each module
names(modu_cols) <- modu_name
V(g1)$color <- V(g1)$modularity
V(g1)$color[!(V(g1)$color %in% modu_name)] <- col_g
V(g1)$color[(V(g1)$color %in% modu_name)] <- modu_cols[match(V(g1)$color[(V(g1)$color %in% modu_name)],modu_name)]
V(g1)$frame.color <- V(g1)$color
```

## 设置边的颜色
边的颜色与模块颜色保持一致 
由于边连接了两个节点，如果两个节点同属于一个模块，我们赋予其模块的颜色 
如果两个两个节点属于不同模块，我们赋予其灰色

```{r}
E(g1)$color <- col_g
for ( i in modu_name){
  col_edge <- cols[which(modu_name==i)]
  otu_same_modu <-V(g1)$name[which(V(g1)$modularity==i)]
  E(g1)$color[(data.frame(as_edgelist(g1))$X1 %in% otu_same_modu)&(data.frame(as_edgelist(g1))$X2 %in% otu_same_modu)] <- col_edge
}
```

```{r}
write.graph(g1, file = "Irrigated farms.graphml", format = "graphml")

```


## 计算网络的layout并输出
我们基于`layout_with_fr`的算法计算layout
当我们的节点数量大于1000时，节点会按照坐标轴排布，出现异常的layout，因此建议设置`grid`参数为`'nogrid'` 
设置`font.main=4`, 使得标题为斜体加粗

```{r}
# 计算 layout
sub_net_layout <- layout_with_fr(g1, niter=999, grid = 'nogrid')
## 可视化并输出
par(font.main = 4)
plot(g1, layout=sub_net_layout, edge.color = E(g1)$color, vertex.size=1.5)
title(main = paste0('Nodes=', length(V(g1)$name),', ','Edges=', nrow(data.frame(as_edgelist(g1)))))
# 添加图例，显示颜色代表的模块
legend("topright", legend = modu_name, col = modu_cols, pch = 14, bty = "n", title = "Modules")

# Exporting the figure; 导出图片
pdf(paste0("Un-irrigated farms-p_0.01-111.pdf"), encoding="MacRoman", width=8, height=8)
par(font.main=4)
plot(g1,layout=sub_net_layout, edge.color = E(g1)$color, vertex.size=1.5)
title(main = paste0('Nodes=',length(V(g1)$name),', ','Edges=',nrow(data.frame(as_edgelist(g1)))))
dev.off()
```


# 网络拓扑参数
```{r}
length(E(g1))  # number of edge
length(V(g1))  # number of nodes
mean(igraph::degree(g1))  # average.degree
diameter(g1, directed=F, weights=NA) # network diameter
vertex_connectivity(g1)    # 节点连通性(vertex_connectivity)
edge_connectivity(g1)      #边连通性 (edge_connectivity)
mean_distance(g1, directed=F)   # average path length
# average.path.length(g1)   # average path length
transitivity(g1)     # 'average' 计算全局的Avg.clustering.coeffi; 'local'计算每个节点的局部聚类系数; 'localundirected'无向图
edge_density(g1, loops=FALSE)    # connectance
centr_betw(g1, directed=F, normalized=T) # Betweenness centrality

# Modularity
fc = cluster_fast_greedy(g1, weights=NULL)
modularity = modularity(g1, membership(fc))
modularity
```



# 多图批量产出
```{r}
pdf(paste0("Example-unirrigated_2.pdf"), encoding="MacRoman", width=15, height=9)
par(mfrow=c(1,3),mar=c(0,0,1,0),font.main=4)
for(i in 1:3){
  g1 <- g[[i]]
  E(g1)$correlation <- E(g1)$weight
  E(g1)$weight <- abs(E(g1)$weight)
  set.seed(007)
  V(g1)$modularity <- membership(cluster_fast_greedy(g1))

  V(g1)$label <- V(g1)$name
  V(g1)$label <- NA
  modu_sort <- V(g1)$modularity %>% table() %>% sort(decreasing = T)

  top_num <- 18
  modu_name <- names(modu_sort[1:18])
  modu_cols <- cols[1:length(modu_name)]
  names(modu_cols) <- modu_name
  V(g1)$color <- V(g1)$modularity
  V(g1)$color[!(V(g1)$color %in% modu_name)] <- col_g
  V(g1)$color[(V(g1)$color %in% modu_name)] <- modu_cols[match(V(g1)$color[(V(g1)$color %in% modu_name)],modu_name)]
  V(g1)$frame.color <- V(g1)$color

  E(g1)$color <- col_g
  for ( i in modu_name){
    col_edge <- cols[which(modu_name==i)]
    otu_same_modu <-V(g1)$name[which(V(g1)$modularity==i)]
    E(g1)$color[(data.frame(as_edgelist(g1))$X1 %in% otu_same_modu)&(data.frame(as_edgelist(g1))$X2 %in% otu_same_modu)] <- col_edge
  }


  sub_net_layout <- layout_with_fr(g1, niter=999,grid = 'nogrid')
  plot(g1,layout=sub_net_layout, edge.color = E(g1)$color,vertex.size=2)
  title(main = paste0('Nodes=',length(V(g1)$name),', ','Edges=',nrow(data.frame(as_edgelist(g1)))))
}
dev.off()
```

